mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('root.urls')),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pergunta_id>/detalhes', views.detalhes, name='detalhes'),
    path('<int:pergunta_id>/votacao', views.votacao, name='votacao'),
    path('<int:pergunta_id>/resultado', views.resultado, name='resultado'),
]

root/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

class Pergunta(models.Model):
    texto = models.CharField(max_length=150)
    data_pub = models.DateTimeField("Data de Publicação: ")

    def __str__(self):
        return self.texto

    def publicada_recentemente(self):
        agora = timezone.now()
        passadas_24h = agora - datetime.timedelta(hours=24)
        return self.data_pub <= agora and self.data_pub >= passadas_24h
    publicada_recentemente.admin_order_field = 'data_pub'
    publicada_recentemente.boolean = True
    publicada_recentemente.short_description = 'É recente?'

class Alternativa(models.Model):
    texto = models.CharField(max_length=100)
    quant_votos = models.IntegerField("Quantidade de Votos: ")
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)

    def __str__(self):
        return "{} ({})".format(self.texto, self.id)

root/models.py
from django.db import models

# Create your models here.

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from .models import Pergunta, Alternativa

# Create your views here.
def index(request):
    lista = Pergunta.objects.all()
    template = loader.get_template('polls/index.html')
    contexto = {'lista_enquetes': lista}
    return HttpResponse(template.render(contexto, request))

def detalhes(request, pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk = pergunta_id)
    contexto = {'enquete': pergunta}
    return render(request, 'polls/detalhes.html', contexto)

def votacao(request, pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk=pergunta_id)
    try:
        id_alternativa = request.POST['escolha']
        alt = pergunta.alternativa_set.get(pk=id_alternativa)
    except (KeyError, Alternativa.DoesNotExist):
        contexto = {
            'enquete': pergunta,
            'error': 'Você precisa selecionar uma alternativa.'
        }
        return render(request, 'polls/detalhes.html', contexto)
    else:
        alt.quant_votos += 1
        alt.save()
        return HttpResponseRedirect(reverse('polls:resultado', args=(pergunta.id,)
        ))

def resultado(request, pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk = pergunta_id)
    contexto = {'enquete': pergunta}
    return render(request, 'polls/resultado.html', contexto)

root/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'root/index.html')

polls/templates/polls/detalhes.html
{% load static %}

<html>
    <head>
        <title>App Enquetes</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/static.css' %}">
    </head>
    <body>
        <h1>Aplicação de Enquetes - DSWeb 2024.1</h1>
        <h2>Enquete # {{ enquete.id }}</h2>
        <h2>{{ enquete.texto }}</h2>
        <p><i>{{ enquete.data_pub }}</i></p>
        {% if error%}
        <dt><b>Erro: {{ error }}</b></dt>
        {% endif %}
        <p>Selecione a alternativa desejada:</p>
        <form action="{% url 'polls:votacao' enquete.id%}" method="post">
            {% csrf_token %}
            <ul>
            {% for alt in enquete.alternativa_set.all %}
                <li><input type="radio" name="escolha" value="{{ alt.id }}" id="alt{{ forloop.counter }}"/><label for="alt{{ forloop.counter }}">{{ alt.texto }}</label></li>
            {% endfor %}
            </ul>
            <input type="submit" value="Registre seu voto"/>
        </form>
        <hr>
        <a href="{% url 'polls:index' %}">Voltar</a>
    </body>
</html>

polls/templates/polls/index.html
{% load static %}

<html>
    <head>
        <title>App Enquetes</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/static.css' %}">
    </head>
    <body>
        <h1>Aplicação Enquetes - DsWeb 2024.1</h1>
        <br>
        <h2>Aluno: Lucas Henrique Barreto Demetrio - 3º Período</h2>
        {% if lista_enquetes %}
            <h3>Lista das Enquetes Cadastradas:</h3>
            <ul>
                {% for p in lista_enquetes %}
                    <li>
                        <a href="{% url 'polls:detalhes' p.id %}">
                            {{ p.texto }}
                        </a>
                    </li>
                {% endfor%}
            </ul>
        {% else %}
            <h3>Nenhuma enquete cadastrada até o momento</h3>
        {% endif %}
    </body>
</html>

polls/templates/polls/resultado.html
<html>
    <head>
        <title>App Enquetes</title>
    </head>
    <body>
        <h1>Aplicação de Enquetes - DSWeb 2024.1</h1>
        <h2>PARCIAL DA Enquete # {{ enquete.id }}</h2>
        <h2>{{ enquete.texto }}</h2>
        <p><i>{{ enquete.data_pub }}</i></p>
        <p>Quantidade de votos por alternativas: </p>
            <ul>
            {% for alt in enquete.alternativa_set.all %}
                <li>
                    {{ alt.texto }} == {{ alt.quant_votos }}
                    voto{{ alt.quant_votos | pluralize }}
                </li>
            {% endfor %}
            </ul>
        <hr>
        <a href="{% url 'polls:votacao' enquete.id %}">Votar novamente?</a>
        <br>
        <a href="{% url 'polls:index' %}">Voltar</a>
    </body>
</html>

root/templates/root/index.html
<html>
    <head>
        <title>Disciplina DSWeb 2024.1</title>
    </head>
    <body>
        <h1>Disciplina DSWeb 2024.1</h1>
        <h3>Aplicações Criadas:</h3>
        <ol>
            <li><a href="/polls/">
                Aplicação de Enquetes
            </a></li>
        </ol>
    </body>
</html>